import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="text-myColor">Home Page</h1>
        {!user ? (
          <SignInButton>Sign in</SignInButton>
        ) : (
          <SignOutButton>Sign out</SignOutButton>
        )}
        {user && <Link href={`/dashboard/${user.id}`}>Dashboard</Link>}
      </main>
    </>
  );
};

export default Home;
